### ISSUE TITLE
[Gallery][Skia.Gtk]CalendarDatePicker(Material)- For the selected date, date(DD) is truncating for the second digit and displaying incorrect date.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11062]
### Current behavior

![Calendardatepicker -Skia](https://user-images.githubusercontent.com/74563602/214894282-54a01416-22d5-456d-950b-3c3be545b671.png)

https://user-images.githubusercontent.com/74563602/214894627-1e94892a-bc93-4e1b-b31e-f08e70a4bc22.mp4

### Expected behavior

![Calendardatepicker -Skia correct](https://user-images.githubusercontent.com/74563602/214895057-a4c39d9c-aabb-4af3-a792-94a33f6f7f3a.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarDatePicker" from the "UI Components" list.
4. Click on the 'Select a date' option.
5. From the  pop-up calendar choose any date.
6. Notice that in the displayed selected date for the DD part the second digit of the date is truncating.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by sakshi173** [comment]
@carldebilly , I retested this bug is still present, please look into this bug.

**Comment by rajamatt** [comment]
This issue is fixed with latest packages on Skia, not quite sure if it was the bump to uno 5.0 or the lightweight styling work that was done on the CalendarDatePicker that fixed it. Anyways, the format of the dates on Skia has gone from M

**Comment by MartinZikmund** [comment]
@rajamatt has the required update already happened?

**Comment by rajamatt** [comment]
@MartinZikmund this was fixed with the updates in this PR: https://github.com/unoplatform/Uno.Gallery/pull/822. I had originally closed that PR because it was duplicate work of an already open PR, but it looks like that other one was also closed for some reason.

Since then it seems like we have changed from using Uno.UI to Uno.WinUI and simply updating the packages doesn't fix it anymore.

Here's how it looked when I updated Uno.UI: 
![image](https://github.com/unoplatform/uno/assets/70542961/1d9ea82f-6755-4b6e-8490-7478f113ca1b)

Here's how it looks when I update Uno.WinUI (truncated):
![image](https://github.com/unoplatform/uno/assets/70542961/24114d4d-ef21-4324-8482-b38812dcaa8b)

**Comment by Youssef1313** [comment]
Still reproduces:

![image](https://github.com/unoplatform/uno/assets/31348972/021bcc3f-f0b0-465a-9112-4f0e106fb0d6)

**Comment by Youssef1313** [comment]
I was able to reproduce yesterday, but couldn't today 👀 

@sakshi173 Can you verify please?

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by sakshi173** [comment]
@Youssef1313, May be by mistaken yesterday I tested this defect for date picker instead of Calendardatepicker, I checked this issue is not properly fixed, now the date is not truncating but going in another line (below is the screenshot). 
![calendardatepicker issue](https://github.com/unoplatform/uno/assets/74563602/d9733420-5c73-439a-9cda-055bfeb101c0)

**Comment by Youssef1313** [comment]
Maybe #14180 can have an effect on this. Let's see once it's merged.

**Comment by Youssef1313** [comment]
I'm no longer able to reproduce after the layout rounding got merged. @sakshi173 Can you verify on your end please?

**Comment by sakshi173** [comment]
Verified this issue is fixed, due to that closing it.
