### ISSUE TITLE
Android DatePicker working only once

### ISSUE THREAD

**Issue by FParenteau** [unoplatform/uno#15267]
### Current behavior

- Add a DatePicker control to a page
- Click on it and select a date then ok
- Click on the date picker -> nothing happen

### Expected behavior

Date selection should be displayed

### How to reproduce it (as minimally and precisely as possible)

- Add a DatePicker control to a page from UnoTemplate
- Click on it and select a date then ok
- Click on the date picker -> nothing happen
[UnoApp9.zip](https://github.com/unoplatform/uno/files/14099752/UnoApp9.zip)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

"Uno.WinUI" Version="5.0.152"

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.8.5

**Comment by FrozDark** [comment]
Same issue

**Comment by FParenteau** [comment]
@MartinZikmund can you please backport in release/stable/5.0

**Comment by MartinZikmund** [comment]
The fix was specific to changes made in 5.1, so maybe there is a bit more to it if it happens in 5.0 too, will investigate

**Comment by MartinZikmund** [comment]
Fixed in #15273

**Comment by jeromelaban** [comment]
@FParenteau the backport has been published in 5.0.153 and later.

**Comment by antoine-hebert** [comment]
Thank you for the quick fix @MartinZikmund & @jeromelaban !

**Comment by martinchrzan** [comment]
I can still reproduce this issue. It is happening when I have datePicker inside another flyout

**Comment by martinchrzan** [comment]
@MartinZikmund & @jeromelaban can you reopen this?
