### ISSUE TITLE
[Gallery][WASM]AutoSuggestBox- In the 'Autosuggest Box with Search Box experience' section, the descriptions of the controls are not displaying on multiple lines.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15967]
### Current behavior

![Auto suggest text not properly display issue](https://github.com/unoplatform/uno/assets/74563602/c7ff6d5a-08af-44f9-9fcf-c77bbad2921f)
![Auto suggest text not properly display issue 2](https://github.com/unoplatform/uno/assets/74563602/f4fc32ee-d18c-4d45-9dbb-f7dae26218f9)

### Expected behavior

![Auto suggest text Correct](https://github.com/unoplatform/uno/assets/74563602/e3552199-12cf-4ce1-9be0-053ec15bd903)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "AutoSuggestBox" from the "UI Component" list.
4. Type any component related letters like 'B' for 'Autosuggest Box with Search Box experience' section.
5. Notice that that the control's descriptions are displaying in a single line, causing the text to become less visible when the screen is resized smaller.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment]
@kazo0 could it be a material style issue?

**Comment by kazo0** [comment]
@jeromelaban 
There's no Material style for `AutoSuggestBox`, might be using the Material `FlyoutPresenterStyle` by accident though.

**Comment by mcNets** [comment]
@jeromelaban @kazo0 AutosuggestBox shows more than one line. If you keep scrolling, you may get an item with 2 lines. Maybe the visual appearance can be improved by adding margin on the right and left.

May I send a PR to this repo?

![image](https://github.com/user-attachments/assets/9f10dd24-d61b-47a6-ac69-e74245da659d)

![image](https://github.com/user-attachments/assets/ec20917e-0ff8-4c89-9a31-10f9a0b3e7a6)

**Comment by agneszitte** [comment]
> @jeromelaban There's no Material style for `AutoSuggestBox`, might be using the Material `FlyoutPresenterStyle` by accident though.

@kazo0 I think you are maybe right here, as I am noticing some purple for the hover state here
![image](https://github.com/user-attachments/assets/ec79bb95-cf77-4724-916a-0ed6b32ede92)

Compare to Fluent theme
![image](https://github.com/user-attachments/assets/5137548e-6c3e-4663-b0f8-d4cf1e24178b)

**Comment by agneszitte** [comment]
> > @jeromelaban There's no Material style for `AutoSuggestBox`, might be using the Material `FlyoutPresenterStyle` by accident though.
> 
> @kazo0 I think you are maybe right here, as I am noticing some purple for the hover state here 

So I think we are maybe just missing
```
                        <StackPanel.Resources>
                            <ResourceDictionary>
                                <ResourceDictionary.MergedDictionaries>
                                    <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                                </ResourceDictionary.MergedDictionaries>
                            </ResourceDictionary>
                        </StackPanel.Resources>
```
(similar to https://github.com/unoplatform/Uno.Gallery/blob/57fdfbda48b7eeab81fa054e3a71d6f2eb551d2a/Uno.Gallery/Views/SamplePages/ContentDialogSamplePage.xaml#L95)

at this level for the AutoSuggestBoxSamplePage
https://github.com/unoplatform/Uno.Gallery/blob/57fdfbda48b7eeab81fa054e3a71d6f2eb551d2a/Uno.Gallery/Views/SamplePages/AutoSuggestBoxSamplePage.xaml#L15

**Comment by mcNets** [comment]
@agneszitte I've added the code you posted, but I'm not sure this is the issue. Initially flyout has a `Width=300`, but when you make the browser window narrow, it automatically changes to a larger size, and then do not recover the original size, and the flyout content remains hidden.

Desktop head behaves the same way.

https://github.com/user-attachments/assets/0fc1e54b-06f5-482f-abe2-b28c5e70b977

**Comment by agneszitte** [comment]
> @agneszitte I've added the code you posted, but I'm not sure this is the issue. Initially flyout has a `Width=300`, but when you make the browser window narrow, it automatically changes to a larger size, and then do not recover the original size, and the flyout content remains hidden.

Thanks for giving it a try @mcNets. Maybe I am mistaken but I think it is still taking the Material theme here and for that reason not using the fluent theme properly (which hopefully could maybe resolve the main issue here in terms of padding, wrapping, etc...)

I will give it a quick try on my side to double-check

**Comment by agneszitte** [comment]
> Thanks for giving it a try @mcNets. Maybe I am mistaken but I think it is still taking the Material theme here visually and for that reason not using the fluent theme properly (which hopefully could normally resolve the main issue here in terms of padding, wrapping, etc...)
> 
> I will give it a quick try on my side to double-check

Related issue: https://github.com/unoplatform/Uno.Gallery/issues/1069#issuecomment-2215227284
And I think as @Xiaoy312 mentioned, the problem may be of the same nature as: https://github.com/unoplatform/Uno.Gallery/issues/1093

**Comment by mcNets** [comment]
@agneszitte I tried to apply the same approach as @morning4coffe-dev did on https://github.com/unoplatform/Uno.Gallery/pull/1123, but it still seems a bit purple.

```csharp
		public AutoSuggestBoxSamplePage()
		{
			this.InitializeComponent();
			Loaded += AutoSuggestBoxSamplePage_Loaded;
		}

		private void AutoSuggestBoxSamplePage_Loaded(object sender, RoutedEventArgs e)
		{
			var boxes = VisualTreeHelperEx.GetDescendants(this)
				.OfType<AutoSuggestBox>()
				.ToList();

			foreach (var box in boxes)
			{
				box.EnsureXamlControlsResources();
			}

			Loaded -= AutoSuggestBoxSamplePage_Loaded;
		}
```

![image](https://github.com/user-attachments/assets/cf595098-cff3-4117-8a40-f1f4a7f54bc3)

**Comment by morning4coffe-dev** [comment]
I have an ongoing PR for fixing this issue https://github.com/unoplatform/Uno.Gallery/pull/1134, but I haven't been able to prioritize. Thank you for looking into this @mcNets. On the image you shared, it is purple as the individual items are still material. We can discuss further, if you want to continue with this issue.

**Comment by mcNets** [comment]
No thank you @morning4coffe-dev , go ahead. I'll take another one. Are you changing the style everytime a new popup appears?

**Comment by morning4coffe-dev** [comment]
As far as I remember, the solution I worked on only functioned after opening the popup for the second time, which is why it hasn't been merged yet. If you'd like, you can take a look at my PR and maybe pick it up if you get any ideas from it.

**Comment by mcNets** [comment]
@morning4coffe-dev If I am not wrong `TextChanged` event if fired before the suggestion list is open.
```csharp
if (sender.IsSuggestionListOpen)
{
	var popup = VisualTreeHelper.GetOpenPopupsForXamlRoot(XamlRoot).FirstOrDefault();
	popup.EnsureXamlControlsResources(true);
	(popup.Child as Border).EnsureXamlControlsResources(true);
}
```
So until TextChanged event is fired again, for example when you add another character or select one option or you clear the TextBox, the style is no applied. Try by press 'b' and when the popup is visible, click 'o', it will change to Fluent.

Set a breakpoint inside the if condition and you'll see it.

**Comment by mcNets** [comment]
@morning4coffe-dev would you mind if I make a modification of your code?

**Comment by morning4coffe-dev** [comment]
@mcNets Not at all, I am happy to collab with you this way! Thank you 😇

**Comment by mcNets** [comment]
@morning4coffe-dev I am not sure I'll be able to send a PR to your PR, I'm used to work alone. 😉

**Comment by morning4coffe-dev** [comment]
@mcNets For sure, no problem, you can create a new PR and we can close off mine, after merging. Hmm... interesting, I am happy to take a look, after you make the PR on why it might not be loading.

**Comment by morning4coffe-dev** [comment]
This issue should be fixed now via https://github.com/unoplatform/Uno.Gallery/pull/1173.

**Comment by agneszitte** [comment]
Thank you so much again, @mcNets, for your valuable contribution to this issue! It's greatly appreciated ❣️

**Comment by agneszitte** [comment]
@jhanvi03 I will let you do some final tests please

**Comment by jhanvi03** [comment]
The issue Still persist with Versions:

 Package	Referenced version	Updated version
Uno.CommunityToolkit.WinUI.UI.Controls	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.203)
Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.203)
Uno.Core.Extensions.Compatibility	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.1.1)
Uno.Core.Extensions.Disposables	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.1.1)
Uno.Sdk	[5.3.96](https://www.nuget.org/packages/Uno.Sdk/5.3.96)	[5.6.0-dev.32](https://www.nuget.org/packages/Uno.Sdk/5.6.0-dev.32)
Package | Referenced version | Updated version
-- | -- | --
Uno.CommunityToolkit.WinUI.UI.Controls | 7.1.200 | 7.1.203
Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid | 7.1.200 | 7.1.203
Uno.Core.Extensions.Compatibility | 4.0.1 | 4.1.1
Uno.Core.Extensions.Disposables | 4.0.1 | 4.1.1
Uno.Sdk | 5.3.96 | 5.6.0-dev.32

![image](https://github.com/user-attachments/assets/e4c7414c-4391-4608-9417-8fb00ce04dcc)
