### ISSUE TITLE
GridView+ListView with FeedView and drag and drop and reordering is not properly working in a desktop target uno project? Strange overlays on high performance maschine from FeedView+GridView

### ISSUE THREAD

**Issue by DevTKSS** [unoplatform/uno#19034]
### Current behavior

https://github.com/user-attachments/assets/8c670565-10a0-40e3-b4a0-4ea34e1e0056

- strange Bottom NavigationBar border overlays on the right FeedView+GridView, the Items are build as Card controls
- strange behavior on drag drop on the left one, its draging the whole element instead of just the ListViewItem, which is a Grid + image+2x TextBlock each Item
- Both FeedView parent items are fed following the docs guide from same source via Injected Service in the Pages Model

added a example of what I would expect it to do from the WinUI Gallery.
You can see the code it is build from also in the video, if something is missing, let me know. Dont know if while beeing beta HotDesign participant it would be allowed to share the project, so its private on github here.

Both FeedView parent items are fed from same Injected Service, which is set up as a IListFeed

strange additionally: running this on a really high performant computer (installed vs 2022 just a few hours ago, with uno etc) is showing the overlays, which I do not expect to happen with that good graphics card

### Expected behavior

added the expected behaviour (drag, drop, reorder) at the end of the video, just look the WinUI 3 Gallery up for bot Elements nested in FeedView.
no overlays or uno extension issue like in the video right in the project explorer

### Workaround

its not disabling build, just strange looking and not showing the estimated behaviour, so workaround for me would be, just not to use drag&drop on any of those things

### Works on UWP/WinUI

None

### Affected platforms

Skia (WPF), Skia (Linux Framebuffer), Windows (WinAppSDK)

### IDE

Visual Studio 2022

### IDE version

Visual Studio 2022 community 17.12.3, .net 9.0.101

### Anything else we need to know?

Target Platforms desktop, windows, but none of the windows ones is building, desktop used regulary for the video to be made. windows target unpackaged is complaining about not knowing AnyCPU as target, because the wizard only added ARM86, x64 and x86 same issue just hidden in the textbox prompt for the packaged one.

The Maschine this is happening on (overlays) is a high end computer with rtx 4070ti graphics and 64gb ram and i9 14900K cpu, which is in idle mode telling from the fans (has AIO also) so in my opinion the graphics capacity of this maschine should not be the problem here.
The Drag-Drop Behaviour is also happening on the lower performance medion i7 with irisX graphics also but not this strange overlay and warning, telling "some component in installer is missing" which complains about uno extension from marketplace which is installed right moments before, waited for package restore, which is defintly correct installed (freshly latest version, just today, done 2x!) logged in for HotReload no problem after reinstalling, before this reinstalling actually the marketplace extension did not work properly but uno-check did tell everything is fine (took very long and runned at the end with -verbose because it was taking really long (30min with 5G?)

**Comment by jeromelaban** [comment]
Thanks for the report. Make sure to avoid reporting multiple problem in the same issue.

The overlay issue that you're seeing is fixed by upgrading to SkiaSharp 3. For the others issues, you can close this one and split into other so we can track individually. Thanks!

**Comment by DevTKSS** [comment]
One quick question to your answer with the overlay: 
I did not here about this version change and on this is the latest UNO.sdk and all of the other stuff just freshly installed. Maybe you can tell what I have to update additionally?
And to the splitting: bit unsure, how small you want to split it up... Could you make the bit clearer for me so I am doing it like you want it to be?

**Comment by jeromelaban** [comment]
You mentioned two behaviors, one for the overlays, the other one for the drag and drop not working properly. The first one is skiasharp related https://github.com/unoplatform/uno/issues/18299. For the drag and drop, make sure to create a new issue and provide [a sample and repro steps](https://platform.uno/docs/articles/uno-howto-create-a-repro.html?tabs=windows-vs). In general, creating a small zip file and attaching it in the issue is good enough.

**Comment by DevTKSS** [comment]
@jeromelaban updated description and added link to the repo, which I checked do correctly not having the bin+obj folders, so should be fine from this?

**Comment by DevTKSS** [comment]
created new app with uno.sdk v 5.6.45 desktop-only target and still having that drag drop issues as told above on both ListView and GridView in FeedView

secondarily, dont know if thats related also to the skia (?) as soon as the application is maximized to fullscreen, the scrolling behaviour of the grid/listview gets very laggy compared to non maximized application state.

was unable to upload the repro, so here is the [link to it](https://technischekonstruktion-my.sharepoint.com/:u:/g/personal/info_technische-konstruktion_com/EVfcas40atFHmnDRWPxSsboBuhoZwnX0uch21NMYqaP8ow?e=p4oX7l) in exchange

**Comment by DevTKSS** [comment]
@jeromelaban overlay issue resolved but if a reordering does not need another event, that does still not work 👀

**Comment by DevTKSS** [comment]
updated issue description

**Comment by DevTKSS** [comment]
@Jen-Uno as the SkiaRenderer issues seems to get sorted currently, may there is any known reasons for this to happen? Do the team need further information or any plans of this to get tackled?

**Comment by DevTKSS** [comment]
@sasakrsmanovic was speaking about this issue with remarkable slowed scrolling if I fullsize the app on win 11 host build to desktop, excluded windows target already because of the annoying resources dictionary with throwing DataType prop not known🤔
Just for your information if the team might research for similar issues to the wasm scrolling one to check whats maybe the core issue of its hopefully just fews

**Comment by DevTKSS** [comment]
@kazo0 Not sure if this is maybe something specific to the FeedView or generally to the ListViewBase inheriting controls 🤔 Do you know this as its coming from the `Uno.Extensions.Reactive.UI` Namespace?

**Comment by DevTKSS** [comment]
Helllo @kazo0 @dr1rrb @jeromelaban ,
while exploring User Inputs (Keyboard) for my current App, I recognized this [Known Issues](https://platform.uno/docs/articles/features/pointers-keyboard-and-other-user-inputs.html#known-issues-for-drag-and-drop-events) section for exctly the Drag+Drop Eventing.
Since the FeedView Control is eitherway a Uno defined API, I would like to suggest that the FeedView should either:
1. Not publish Drag-Drop Props/Eventing at all
2. Redirect captured those Events to any top level child control so we (from consumer side) can capture and Handle them in our controls code

This could potentially solve this issue, would you be able to check this?

**Comment by DevTKSS** [comment]
@MartinZikmund I seen you closing/are about to close the "Drag Drop" Issue for UIElement. I didn't heared anything about this issue right here, from the team, for a very long time and would be interested in current information about the status.

Is Uno evaluating, and *for when* are you planning (month or more years?), to fix this in future release versions?

**Comment by MartinZikmund** [comment]
Thanks for the patient follow-up here, and apologies for the slow response. Looking at how this has evolved, the remaining scoped ask is about FeedView's drag/drop event surface (whether it should redirect/forward those to the inner ListViewBase, or not project them at all), and FeedView ships from Uno.Extensions (the Reactive.UI MVUX package), not from this repo. To make sure it lands in front of the right maintainers, could you please reopen this in https://github.com/unoplatform/uno.extensions with the FeedView-specific repro? If you do run into a concrete ListViewBase-level drag/drop bug that reproduces without FeedView in the tree, a separate, focused issue here is very welcome and we'll track it independently.
