### ISSUE TITLE
Selecting 'WinAppSdk Unpackaged' from the targets dropdown automatically defaults to 'WinAppSdk Packaged'

### ISSUE THREAD

**Issue by erikvilima** [unoplatform/uno#19410]
### Current behavior

From a newly created app using the Wizard + blank template:

https://github.com/user-attachments/assets/d7abcc1a-b743-46ea-a675-bc2ab03b5828

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.Sdk: 5.6.20

**Comment by jeromelaban** [comment]
This is a known issue here: https://developercommunity.visualstudio.com/t/WinAppSDK-Unpackaged-profile-cannot-be-s/10643735

**Comment by agneszitte** [comment]
Workaround mentioned by @dr1rrb:
Replace the `<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst;net9.0-windows10.0.26100;net9.0-browserwasm;net9.0-desktop</TargetFrameworks>` node by a single `<TargetFramework>net9.0-windows10.0.26100</TargetFramework>` in duplicate https://github.com/unoplatform/uno.studio/issues/762.

**Comment by Darsh0307** [comment]
@agneszitte @jeromelaban @dr1rrb 

 After replacing the target framework in .csproj as mentioned in this comment https://github.com/unoplatform/uno/issues/19410#issuecomment-2649447729

I am able to run the app when having `WinApp sdk Unpackaged`as the debugging target. But there are some errors shoiwng when debugging.  If we click on yes then it  successfully opens the app and even the HR also works as expected.

<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/c6fb15ed-2af5-4caf-aa02-d797ca351e15" />

**Comment by jeromelaban** [comment]
Indeed, this is unrelated to this specific issue. VS 17.14 may be causing additional issues.

**Comment by MartinZikmund** [comment]
This should now be working correctly

**Comment by Jen-Uno** [comment]
@agneszitte not sure about this one

**Comment by agneszitte** [comment]
> [@agneszitte](https://github.com/agneszitte) not sure about this one

@jhanvi03 I will let you re-test this one with latest versions please

**Comment by rajamatt** [comment]
Still happening in a newly created blank app (with the Windows platform enabled) with VS VSIX [6.1.8](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=169949&view=results) using the wizard.

https://github.com/user-attachments/assets/5fee6a52-1cfd-4ec6-9f59-a2cc33ef366e

**Comment by agneszitte** [comment]
> Still happening in a newly created blank app (with the Windows platform enabled) with VS VSIX [6.1.8](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=169949&view=results) using the wizard.

@rajamatt are you using latest VS version when testing with latest Uno.Sdk and VS VSIX versions ? Also same behavior with latest VS Preview please ?

**Comment by rajamatt** [comment]
@agneszitte I just retried using latest stable VS 2022 version 17.4.7 with uno sdk 6.1.12 and VS VSIX 6.1.12. Same behavior as before (unpackaged switches to packaged). With VS 2022 version 17.4.7 Preview 1.0 it is also the same behavior as before.

Interestingly, if I remove the Uno Platform extension from VS, then switching to other targets (Wasm, Desktop) becomes unstable (they switch back sometimes). **But even more is that, without the Uno Platform extension, if I select Unpackaged it doesn't switch to Packaged like in this issue (but switching to Wasm, Desktop is buggy).**

**Comment by rajamatt** [comment]
Still not fixed with `VS 2022 17.14.12` or preview version `VS 2022 17.14.12 Preview 1.0` along with uno templates `6.2.21` and latest VSIX `6.2.7`.

It doesn't seem like we are doing anything special on our end that would cause this. For that reason I'm tagging this as blocked and we will likely need to poke MS again since their fixes have not worked (see [archived discussion on their forum](https://developercommunity.visualstudio.com/t/WinAppSDK-Unpackaged-profile-cannot-be-s/10643735)).
