### ISSUE TITLE
[iOS 5.6 regression] Parent control resources completely ignored beyond direct parent

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#19825]
### Current behavior

Styles (both implicit and specifically referenced via `{StaticResource}`) added to any parent other than the direct parent are ignored. This is an Uno 5.6 regression (works in `v5.5.62`).

### Expected behavior

Child controls should be able to access styles from parent resource dictionaries beyond their direct parent.

### How to reproduce it (as minimally and precisely as possible)

```xml
<Page ...>
  <Page.Resources>
    <!-- Style is ignored -->
    <Style TargetType="Button">
      <Setter Property="Background" Value="Red"/>
    </Style>
  </Page.Resources>

  <ScrollViewer>
    <ScrollViewer.Resources>
      <!-- Style is ignored -->
      <Style TargetType="Button">
        <Setter Property="Background" Value="Red"/>
      </Style>
    </ScrollViewer.Resources>
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center" utu:SafeArea.Insets="VisibleBounds">
      <!-- Style is only respected if this is uncommented -->
      <!--<StackPanel.Resources>
        <Style TargetType="Button">
          <Setter Property="Background" Value="Red"/>
        </Style>
      </StackPanel.Resources>-->
      <Button Content="Test Content"/>
    </StackPanel>
  </ScrollViewer>
</Page>
```

Sample project: [TestUno.zip](https://github.com/user-attachments/files/19588563/TestUno.zip)

Notice the style is not applied on iOS but works fine everywhere else.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

6.0.0-dev.132, 5.6.51, 5.6.19

### Affected platforms

iOS

**Comment by mikernet** [comment]
@jeromelaban @ajpinedam I updated to Uno.SDK 5.6.54 (I assume that includes this fix?) and now I am seeing this behavior on Android.

**Comment by mikernet** [comment]
Should I open a new issue for Android or can we reopen this and I'll change the title/info to reflect that it also happens on Android?

**Comment by ajpinedam** [comment]
Hi @mikernet, I want to validate if I correctly understood. The issue reported in this ticket, when using Uno.SDK 5.6.54 is working fine for iOS but not for Android, right? Meaning that for iOS, it is fixed

If that's the case, please open a new issue. Please also feel free to mention this ticket for reference.

**Comment by mikernet** [comment]
@ajpinedam Is your PR published as part of Uno.SDK `5.6.54`? Neither iOS nor Android are working for me. If you take the attached test project zip above and just update the Uno.SDK version it still does not appear to be fixed.

**Comment by ajpinedam** [comment]
@mikernet It believed it was part of `Uno.SDK` **5.6.54**, but it seems it's not. I validated your sample with one of the latest dev `Uno.SDK` (6.1.0-dev.64) and it worked as expected. Let me check why `Uno.SDK` **5.6.54** does not have this fix.

Cc: @jeromelaban, can you help me figure it out?

**Comment by mikernet** [comment]
Created this issue for the same problem on Android: https://github.com/unoplatform/uno/issues/20181

**Comment by jeromelaban** [comment]
@mikernet the update has not been published in 5.6 yet. We'll do an update 5.6 after our current release.
