### ISSUE TITLE
Android WebView does not respect AdjustResize with Uno.Sdk 5.6.51

### ISSUE THREAD

**Issue by yeahg-dev** [unoplatform/uno#19858]
### Current behavior

When using "Uno.Sdk": "5.6.51" on Android, setting `SoftInputMode = AdjustResize` has no effect when displaying a WebView.
This causes the on-screen keyboard to cover focused input fields, especially when the HTML content contains forms or interactive inputs.
In previous versions like 5.6.22, the keyboard triggered proper layout resizing and scrolling as expected.

https://github.com/user-attachments/assets/9a039f87-908e-469c-81e0-9ac935c72e69

### Expected behavior

`SoftInputMode = AdjustResize` should shrink the WebView’s visible area and allow input elements (like <input>, <textarea>) to stay visible when the keyboard is shown — just like it did in version 5.6.22.

### How to reproduce it (as minimally and precisely as possible)

https://github.com/yeahg-dev/UnoAndroidWebViewExample

### Works on UWP/WinUI

None

### Affected platforms

Android

### IDE

Visual Studio Code

**Comment by MartinZikmund** [comment]
@morning4coffe-dev Can you please try to find out which specific PR between 5.6.22 and 5.6.51 broke this behavior?

**Comment by DosangGu** [comment]
Are there any progress with this issue? It is blocking us from upgrading to newer versions.

**Comment by ajpinedam** [comment]
We found that this issue is coming from Android. 

The latest version of Uno implemented the Edge-to-Edge feature https://developer.android.com/develop/ui/views/layout/edge-to-edge. Note: Android enforces this feature on Android 35 on devices running Android 15 or later.

There is an ongoing issue when this feature is enabled with WebViews; more information is available [here](https://issuetracker.google.com/issues/311256305?pli=1).

We pushed a PR, but this might not be the final fix, and we are looking for a workaround so that you can deal with this issue directly from the apps. We will be updating you soon.

cc: @DosangGu @yeahg-dev

**Comment by ajpinedam** [comment]
We found a workaround for those having this issue on Android. 

On your Uno Platform solution, navigate to the `MainActivity.Android` file and override/update the `OnCreate()` method adding this line `WindowCompat.SetDecorFitsSystemWindows(Window, true);` near the end.

with the change it should look like this:

```csharp
protected override void OnCreate(Bundle bundle)
{
    base.OnCreate(bundle);
    WindowCompat.SetDecorFitsSystemWindows(Window, true);
}
```

This is until Google fixes the issue on their side. We will update our docs to include this as a known issue and the workaround.

cc: @DosangGu  @yeahg-dev

**Comment by Jen-Uno** [comment]
@ajpinedam  has the documentation been updated?

**Comment by ajpinedam** [comment]
> [@ajpinedam](https://github.com/ajpinedam) has the documentation been updated?

Yes, under PR https://github.com/unoplatform/uno/pull/20713 which is still pending to be merged.

**Comment by GabrielLaban** [comment]
The issue is still not resolved
Tested with latest stable SDK version 6.1.14.

Tested with:
Templates/SDK: 6.1.14
Platfroms(s): Android
VS VSIX: none
IDE: none
OS: Android

Repro: 

[Issue19858.zip](https://github.com/user-attachments/files/21145540/Issue19858.zip)

**Comment by mediamubarakcc-blip** [comment]
using `SafeArea.Insets = "SoftInput"` achieves the same result. Please check on that. [doc](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/SafeArea.html)
I haven't tested it with WebView but i would assume it works with it too.
