### ISSUE TITLE
[skia-Wasm] `DatePicker` does not correctly update to selected value

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#20693]
### Current behavior 🐛

When user selects a date in `DatePicker`, it is not immediately reflected.

https://github.com/user-attachments/assets/13b3aa5e-0ac7-4b88-b9e9-abb2457186c6

### Expected behavior 🎯

Should work reliably.

### How to reproduce it (as minimally and precisely as possible) 🔬

1. Open a `DatePicker`
2. Select date and quickly confirm
3. **Notice the selected date is not reflected**

### Workaround 🛠️

N/A

### Renderer 🎨

- [x] Skia
- [ ] Native

### Affected platforms 📱💻🖥️

All platforms 🌍

### Uno.Sdk version (and other relevant versions) 📦

[6.1.0-dev.195](https://www.nuget.org/packages/Uno.Sdk/6.1.0-dev.195)

### IDE version 🧑‍💻

VS 2022

**Comment by jeromelaban** [comment]
The date is reflected, but after a few seconds, it seems.

**Comment by MartinZikmund** [comment]
I think it may be inertia-related

**Comment by dr1rrb** [comment]
Not sure to understand what you are doing in the video @MartinZikmund.

Inertia is only about touch-scrolling while here you are using mouse, so probably not related

**Comment by MartinZikmund** [comment]
@dr1rrb yes I did not say that correctly. On Skia `ScrollViewer` now applies the composition strategy on animated `ChangeView` and when you do the selection, `DatePicker` scrolls the spinner towards the selected value. But if the picker is closed before it reaches that value, it does not get selected (visually). If I wait for the animation to finish before closing the popup, the value is shown correctly. My thinking was it could be related to the fact that the strategy updates values at different times than the non-composition one.

**Comment by Xiaoy312** [comment]
The issue is only reproducible on skia-wasm so far. _It may be possible under other skia-platforms, but I had no success._
The issue happens specifically when the LoopingSelector from the flyout is still spinning to the selected value and you confirm (click on `✓`-checkmark, not outside) the changes. So long as the scrolling didnt fully stop when confirming, you can repro it. _We can't repro on skia-desktop, probably due to lack of rendering/performance pressure._
The DatePicker will receive the value immediately (confirmed via SelectedDate binding and SelectedDateChanged).
It is also not just the DatePicker that is impacted, another TextBlock bound to the SelectedDate is also not re-rendered.

![Image](https://github.com/user-attachments/assets/4845770b-36d9-425f-aade-ca9d135eb052)
repro: [u20693.zip](https://github.com/user-attachments/files/21319101/u20693.zip)

edit: changing foreground instead of background will cause the text to re-render with the correct value:
![Image](https://github.com/user-attachments/assets/8486c472-f58f-470c-b41d-832bc0eee1d3)
<details>
<summary>just change this method form the repro:</summary>

```cs
private void CycleBackground(object sender, RoutedEventArgs e)
{
	if ((sender as Button)?.Tag is FrameworkElement fe)
	{
		var (brush, setter) = ((Brush,Action<Brush>))(fe switch
		{
			DatePicker dp => (dp.Foreground, x => dp.Foreground = x),
			TextBlock tb => (tb.Foreground, x => tb.Foreground = x),
			Border { Child: TextBlock tb } => (tb.Foreground, x => tb.Foreground = x),

			_ => throw new ArgumentException(),
		});

		setter(
			(brush as SolidColorBrush)?.Color.R == 255
				? new SolidColorBrush(Colors.Blue)
				: new SolidColorBrush(Colors.Red)
		);
	}
}
```
</details>

**Comment by Xiaoy312** [comment]
maybe related?: https://github.com/unoplatform/uno.hotdesign/issues/4327
^ the fix for that should in the repro, but didnt seem to work for this particular instance..

**Comment by MartinZikmund** [comment]
Could it be related to some text invalidation edge case @ramezgerges?

**Comment by ramezgerges** [comment]
This is fixed between Uno.Sdk 6.1.0-dev.244 and 246 which correspond to Uno.Winui 6.1.0-dev.567 and 6.1.0-dev.667 which correspond to commits 696045c9ea350cf2235ce4b46b13e72c6ea32098 and 133f7d9f6c10d3117a993f5d96383ac4d6360831.
For some reason the repro never reproduces inside SamplesApp and even in an external app, it turns out that I need to do `git clean -fdx` after every Uno.Sdk change, otherwise weird things happen where it always repros (even on Uno.Sdk version that should have the fix) or it never repros.

**Comment by ramezgerges** [comment]
The fix is https://github.com/unoplatform/uno/pull/20808 but it feels more like a coverup than a fix. The fix being that PR means that it's likely that after measuring and/or arranging, we're not invalidating the textblock paint.

**Comment by ramezgerges** [comment]
It's actually fine. The problem depended on a race where we invalidated both Measure and Paint but we needed Measure to always happen first. With #20808 that is guaranteed to happen.

**Comment by jhanvi03** [comment]
Re-opening the issue as it still persist on latest Gallery skia Canary. Upon selecting dates oftan it gets updated as "selectedDate - 1"

https://github.com/user-attachments/assets/0d0cc7a1-90e3-4358-8dac-00ecadca8810

**Comment by ramezgerges** [comment]
@jhanvi03 Could you please test this again with the latest dev version?

**Comment by jhanvi03** [comment]
Issue is still reproducible on latest Gallery canary:

tested with: 
Browser: Chrome
Skia Gallery Build: https://dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_build/results?buildId=181945
OS: Mac


https://github.com/user-attachments/assets/87ab892d-0bfc-4cc2-b016-d790d8a079cf
