### ISSUE TITLE
[WASM][Windows] Uno.UI.FluentTheme.v2 assembly fails to AOT under Windows

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#6152]
## Current behavior

Cannot build for InterpreterAndAOT on latest Uno.Wasm.Bootstrap package, build fails with error message like,

1>Uno.UI is using Roslyn generators
1>AotBuildBootstrapUpdate.Wasm -> C:\Users\PNary\source\repos\AotBuildBootstrapUpdate\AotBuildBootstrapUpdate.Wasm\bin\Release\net5.0\AotBuildBootstrapUpdate.Wasm.dll
1>C:\Users\PNary\.nuget\packages\uno.wasm.bootstrap\3.0.0-dev.85\build\Uno.Wasm.Bootstrap.targets(172,5): error : System.Exception: Failed to generate AOT layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
1>C:\Users\PNary\.nuget\packages\uno.wasm.bootstrap\3.0.0-dev.85\build\Uno.Wasm.Bootstrap.targets(172,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v9c13b3eb17d2f6c3f78fb2dbef21ff8ebda4de1e.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 788
1>C:\Users\PNary\.nuget\packages\uno.wasm.bootstrap\3.0.0-dev.85\build\Uno.Wasm.Bootstrap.targets(172,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v9c13b3eb17d2f6c3f78fb2dbef21ff8ebda4de1e.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 224

## Expected behavior

Should build

## How to reproduce it (as minimally and precisely as possible)

Attempt to build attached project in Release mode and observe failure.  Can build in Debug mode.

[AotBuildBootstrapUpdate.zip](https://github.com/unoplatform/uno/files/6594128/AotBuildBootstrapUpdate.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.Wasm.Bootstrap 3.10
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

I cannot reproduce the error.

It seems that you're running this from a CI system on Windows, which uses the new experimental emscripten for Windows support, could you provide the binlog for that build ?

If you still want to try out on your machine, you will need to install [Python from Windows Store](https://www.microsoft.com/store/productId/9P7QFQMJRFP7), or manually through [Python's official site](https://www.python.org/downloads/).

In all cases, you can keep using the 2.1.0 stable bootstrapper package.

**Comment by peternary** [comment]
Here's the binlog, I'll install Python and see if that resolves the issue.

[msbuild.zip](https://github.com/unoplatform/uno/files/6599035/msbuild.zip)

**Comment by peternary** [comment]
Installing Python did not resolve the issue (I tried both Windows Store and official site version, and rebooted afterward just in case).  I'm getting this issue both from running msbuild on the command line and trying to build from within Visual Studio.

**Comment by jeromelaban** [comment]
Thanks for the update. Could you post the new msbuild.binlog file as well ?

**Comment by peternary** [comment]
New binlog:

[msbuild.zip](https://github.com/unoplatform/uno/files/6618648/msbuild.zip)

**Comment by DierkDroth** [comment]
@jeromelaban this appears to be a regression, no? Are there any plans to address this any time soon or is this beyond UNO's control?

**Comment by jeromelaban** [comment]
@DierkDroth we're working on it the new experimental bits. You can always use the last stable for the bootstrapper, which works properly.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban

**Comment by jeromelaban** [comment]
@peternary The last version of the Uno Bootstrapper (3.0.0-dev.95) contains additional fixes to troubleshoot the issue.

Your setup may be in an unstable state as a result of the previous bits, and to get back to a stable state you'll need to remove the folder named `%USERPROFILE%\.uno\emsdk`, the restart a build. This may have happened because python was not installed on the first run, and is now fixed in the latest bits.

**Comment by peternary** [comment]
@jeromelaban Deleted that folder and attempted again, it's still failing to build.  I'm now getting the message "The --appdir= argument is required." in my error output.  I can produce another binlog if that would help.

**Comment by jeromelaban** [comment]
Thanks Peter, yes if you can provide the binlog it will help.

**Comment by peternary** [comment]
Here you go!

[msbuild.zip](https://github.com/unoplatform/uno/files/6664397/msbuild.zip)

**Comment by jeromelaban** [comment]
Thanks! We've added some additional logging to understand why this is not working on your end. Can you try again with 3.0.0-dev.101, and provide the binlog again ?

**Comment by peternary** [comment]
Here's binlog from 3.0.0-dev.101

[msbuild.zip](https://github.com/unoplatform/uno/files/6727078/msbuild.zip)

**Comment by jeromelaban** [comment]
Thanks for the update. I've just now noticed that you changed the monosdk paths, can you clear that folder and let the bootstrapper rebuild it?

**Comment by peternary** [comment]
Wiped the C:\MonoWasmSDKs and attempted a rebuild, binlog attached

[msbuild.zip](https://github.com/unoplatform/uno/files/6770688/msbuild.zip)

**Comment by jeromelaban** [comment]
Thanks for the update and patience.

Indeed the clean worked this time, the build got lots further. This time it looks the .NET runtime is failing, it could be something the .NET Team has fixed in an updated build. We'll have to validate again soon.

**Comment by DierkDroth** [comment]
@jeromelaban where are we at on that issue? Is it still pending?

**Comment by jeromelaban** [comment]
@DierkDroth none of the recent runtime fixes are addressing this issue, we'll follow up with the runtime team.

**Comment by DierkDroth** [comment]
That's odd :-( Thanks for following up @jeromelaban

**Comment by peternary** [comment]
@jeromelaban Did some testing related to this trying to do an InterpreterAndAot build with .net 6 RC1 on latest packages, seems to be an issue with linking.  In a test project I get error:

1>    [00:04:22.7313904] [730/754] [AOT] .\linker-out\Uno.UI.FluentTheme.v2.dll -> ./Uno.UI.FluentTheme.v2.dll.bc.tmp
1>    [00:04:22.7314267] FAILED: Uno.UI.FluentTheme.v2.dll.bc.tmp

And removing the \<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /> from App.xaml resolves the issue, permitting me to build in test project.

Trying to build our main project in .net 6 I encounter similar error with SkiaSharp

1>    [00:04:53.5455418] [769/777] [AOT] .\linker-out\SkiaSharp.dll -> ./SkiaSharp.dll.bc.tmp
1>    [00:04:53.5455856] FAILED: SkiaSharp.dll.bc.tmp

All tests succeed with uno-check --preview on latest uno-check

I can provide full build log, test project, or binlog if it helps.

**Comment by jeromelaban** [comment]
I was just updating the documentation for this issue, to let you know how to workaround it, now that we've released the bootstrapper 3.0.0. I'll give more details soon.

**Comment by peternary** [comment]
We are able to build if we disable AOT for Fluent styles and Skia

**Comment by nor0x** [comment]
i'm curious @peternary - which assemblies did you have to add include with `<MonoRuntimeMixedModeExcludedAssembly>` - i'm having the same issue in an Uno WebAssembly project referencing `SkiaSharp`, currently i have these entries in my csproj but i'm still having the issue.


```
<ItemGroup>
    <MonoRuntimeMixedModeExcludedAssembly Include="SkiaSharp.Views.Uno" />
    <MonoRuntimeMixedModeExcludedAssembly Include="SkiaSharp" />
    <MonoRuntimeMixedModeExcludedAssembly Include="Uno.UI.Lottie" />
    <MonoRuntimeMixedModeExcludedAssembly Include="Uno.UI.FluentTheme.v1" />
    <MonoRuntimeMixedModeExcludedAssembly Include="Uno.UI.FluentTheme.v2" />
</ItemGroup>
```

@jeromelaban building via WSL is unfortunately not an option in my case.

**Comment by peternary** [comment]
@nor0x, I've got even fewer excluded assemblies than you.  Here they are.

<ItemGroup>
	<MonoRuntimeMixedModeExcludedAssembly Include="Uno.UI.FluentTheme.v1" />
	<MonoRuntimeMixedModeExcludedAssembly Include="Uno.UI.FluentTheme.v2" />
	<MonoRuntimeMixedModeExcludedAssembly Include="SkiaSharp" />
</ItemGroup>

**Comment by jeromelaban** [comment]
@nor0x you may be having a different issue then. Can you post your msbuild.binlog file ?
