### ISSUE TITLE
[Android] Pivot completely broken on Android

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7261]
### Current behavior

1) `Pivot` does not size to `PivotItem` content size correctly. If a pivot is put into an auto height grid column, only the header is shown.
2) If you manually set a `MinHeight` on the `Pivot` to force it to show something and put a `ScrollViewer` inside a `PivotItem` it does not properly size the content inside the scrollviewer that is stretched horizontally - the content stretches too far to the right so it either does not center correctly if `HorizontalScrollMode="disabled"` or it horizontally scrolls.

### How to reproduce it (as minimally and precisely as possible)

See the following in test project where it reproduces the problem:
1) [This](https://github.com/mikernet/UnoTest/blob/a31df9a9c33e2dbff9a87502487280fe634d59b2/iRatio.Client/iRatio.Client.Shared/Roots/LoginRoot.xaml#L18) is the grid row that does not size correctly to the pivot content.
2) [This](https://github.com/mikernet/UnoTest/blob/a31df9a9c33e2dbff9a87502487280fe634d59b2/iRatio.Client/iRatio.Client.Shared/Roots/LoginRoot.xaml#L21) `MinHeight` is required so that the `Pivot` shows anything other than the headers.
3) [This](https://github.com/mikernet/UnoTest/blob/a31df9a9c33e2dbff9a87502487280fe634d59b2/iRatio.Client/iRatio.Client.Shared/Roots/LoginRoot.xaml#L73) `ScrollViewer` incorrectly sizes horizontally stretched content causing it to be bigger than the available scrollviewer area and thus it pans horizontally.

### NuGet package version(s)

Uno.UI 3.11.0-dev.248

### Affected platforms

Android

**Comment by jeromelaban** [comment]
Thanks for the report. 

The pivot control current implementation has mainly been developed to be stretched in its container, not placed to an auto context.

We have a task to port the WinUI pivot control so that it behaves like the WinUI control, but it was not listed. I'll rename this issue to reflect this.

**Comment by mikernet** [comment]
In my app I have the style set to the UWP template though and it still isn't sizing correctly.

**Comment by jeromelaban** [comment]
It's not the issue, it's the underlying C# implementation that is not supporting all the features that the UWP template provides.

**Comment by emceelovin** [comment]
as said, Pivot's won't auto size to a grid row. they'll auto size to a layout. they're mainly used by themselves, but if you need it to automatically size, put it inside a stack layout and then put that inside a *(take up remaining space) grid row/column. the layout should size to the grid row/column(which will take up the whole page) and then the pivot will size to that. i mainly have them inside a page by itself. In which the page is inside a Frame controlled by a NavigationView. then obviously you put Page objects inside your <PivotItem>'s for automatic nav/thumb swiping free of charge. hope this helps!

**Comment by mikernet** [comment]
@emceelovin I'm not sure what you mean. It works fine on iOS, WASM and UWP. Android is the only platform it doesn't correctly work on.

I can't do what you're describing because the pivot needs to be inside a scroll viewer so that the whole pivot moves with the page. Having the pivot headers fixed at the top of the page is not acceptable for the layout we have as it would take up too much room at the top of the page.

I ended up just redoing the pivot with styled radio buttons and panels that show/hide with bindings to the radio button selected state.

**Comment by emceelovin** [comment]
Move with the page? In what direction? Pivot's expand beyond the width of a screen on android for me. Then you can swipe through them and the PivotItem's content pages will carousel. Are you talking about inside a vertically oriented ScrollView? you still don't need a Grid either way. you can have Page -> ScrollViewer(Vertical) -> Pivot and it'll work just fine. I don't use Pivot's inside of a Grid. that defeats the purpose of a Pivot. I don't have anything to visually go on, but just based on the purpose of a Pivot, i don't really see what would justify putting one inside of a Grid. In reference to the docs, a Pivot will always carousel if the headers do not fit within the width of its parent. If they don't, they will expand beyond the width of the screen and cause PivotItem content to do the same. I don't believe there's a way to fix that with control properties. I can live with the PivotItem content not being constained to the width of the screen, but I would also like to have it constrained to the screen if it was possible with control properties. You could use a Pivot inside of a Grid, and have a vertical ScrollView in the first row so that the pivot can be scrolled horizontally, and then use a Frame in the second control. You'd have to handle the navigation manually though, but that's not terrible. Is that what youre trying to do? overflow the Pivot headers but not the content?

This is just a Pivot directly inside a Page with Page's inside the PivotItem's
![image](https://user-images.githubusercontent.com/55720292/149422688-4ada2832-c301-42bd-b13f-db26b6f00693.png)

**Comment by mikernet** [comment]
I'm talking about vertical scrolling. When you swipe the page down, the whole pivot including the headers should move, not just the content inside the pivot item.

**Comment by mikernet** [comment]
I've already worked around the issue so I don't really need help with that. The issue just needs to be fixed so the Android pivot has the same layout behavior as the other platforms.

**Comment by MartinZikmund** [comment]
Still relevant

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** Feature request to import the WinUI Pivot control.
